### ISSUE TITLE
Multiple subreddits

### ISSUE THREAD

**Issue by Khyretos** [WoophRadu/DiscordRedditSubmitter#1]
Hey there,

is it possible to have it work with multiple subreddits?

![image](https://user-images.githubusercontent.com/25864917/99061732-45264e00-25a2-11eb-8038-61e8583ed8c8.png)

as i understand from this it can only subscribe to one subreddit, and i would like it to subscribe to multiple subreddits is that possible?

thanks in adavance.

**Comment by WoophRadu** [comment]
Delete your config and default_config and download again. Reconfigure using instructions in the config files and it should work :)

**Comment by Khyretos** [comment]
o damn, thanks man i see you updated the bot entirely, nice!
