### ISSUE TITLE
Problems with discord authentication

### ISSUE THREAD

**Issue by Khyretos** [WoophRadu/DiscordRedditSubmitter#3]
Bot has a problem when connecting to discord here is a screenshot.

![image](https://user-images.githubusercontent.com/25864917/100786739-dacf3380-3412-11eb-98bb-21022f6965de.png)

it says it has problems with the token for some reason.

**here the log file:**
import logging
loglevel = 20

def setlevel(level):
    global loglevel
    loglevel = int(level)

def log(msg, level="info"):
    if level == "debug" and loglevel <= 10:
        print("[DEBUG] " + msg,flush=True)
        logging.debug(msg)
    elif level == "info" and loglevel <= 20:
        print("[INFO] " + msg,flush=True)
        logging.info(msg)
    elif level == "warning" and loglevel <= 30:
        print("[WARNING] " + msg,flush=True)
        logging.warning(msg)
    elif level == "error" and loglevel <= 40:
        print("[ERROR] " + msg,flush=True)
        logging.error(msg)
    elif level == "critical" and loglevel <= 50:
        print("[CRITICAL] " + msg,flush=True)
        logging.critical(msg)

**Comment by WoophRadu** [comment]
Please make sure you are setting your Bot's Token correctly. You need the **Bot Token**, not the **Client Secret**! It's easy to confuse the two. 

Go to the [Discord Developer Portal](https://discord.com/developers/applications), create an application there or select the one you already created. Then, on the right, you will have a tab that says "Bot". Make sure you have a Bot, and if not, click **Add Bot**. That will create a Discord Bot account. There, you will find a field that says **TOKEN**. You copy that, and you paste it into your config.

Find your **Token** here:
![image](https://user-images.githubusercontent.com/5834946/100791543-0efe2080-3422-11eb-9acd-1040203ff4d8.png)


Please confirm you're not mistaking it for the **client secret**, which is found here:
![image](https://user-images.githubusercontent.com/5834946/100791802-63090500-3422-11eb-92be-8feff05742eb.png)
This is the wrong one!

**Comment by Khyretos** [comment]
yea i did that but it still has issues.

![image](https://user-images.githubusercontent.com/25864917/100792064-613b4380-341a-11eb-96bd-3128f79d1fb6.png)

i have several bots that i self host so i know which token i needed to paste but its still presenting problems for some reason, i also gave the bot admin permisions just in case 
![image](https://user-images.githubusercontent.com/25864917/100792190-90ea4b80-341a-11eb-8959-3c6b4253a386.png)

**Comment by WoophRadu** [comment]
I added better clarity for the issue in the logs, in commit dde2fae. Please update (redownload or pull the repo), and try again. Please also paste the correct log (file "bot.log", not "logger.py"), so I can better understand the problem :)

**Comment by Khyretos** [comment]
**now i get this:**
![image](https://user-images.githubusercontent.com/25864917/100795940-289e6880-3420-11eb-9536-fe4ff3dd043a.png)

**and here is the log:**
[INFO @ 2020-12-01 09:55:55 PM] --- INITIALIZING ---
[WARNING @ 2020-12-01 09:55:55 PM] Config file config.ini not found, generating a new one from default_config.ini
[INFO @ 2020-12-01 09:55:56 PM] Logged into reddit as /u/kiewirevo
[WARNING @ 2020-12-01 09:55:56 PM] PyNaCl is not installed, voice will NOT be supported
[INFO @ 2020-12-01 09:55:56 PM] logging in using static token
[INFO @ 2020-12-01 09:55:56 PM] Cleaning up tasks.
[INFO @ 2020-12-01 09:55:56 PM] Closing the event loop.
[CRITICAL @ 2020-12-01 09:55:56 PM] There was an error while connecting the bot to Discord. Either your login token is invalid, or idk. Exiting in 5 seconds.
[CRITICAL @ 2020-12-01 09:55:56 PM] Exception passed: <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'> Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1122)')]

**Comment by WoophRadu** [comment]
This seems to be an issue outside of my control, either with the SSL certificates that are included with your version of Windows or Python. See https://github.com/Rapptz/discord.py/issues/4159#issuecomment-640107584 and try following those instructions, or the other ones in that issue.

**Comment by Khyretos** [comment]
THANK YOU!!!!, it worked 
![image](https://user-images.githubusercontent.com/25864917/100816691-f3f1d780-3446-11eb-915c-a4d7f45cff2f.png)
